# Kan Vladislav AIN-2-22

# Lab 2

In [51]:
import numpy as np

In [52]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [53]:
b= np.array([[1.2, 2.5], [0.5, 4.5]])
b

array([[1.2, 2.5],
       [0.5, 4.5]])

In [54]:
c= np.array([[1, 2, 5], [5, 6, 5]])
c

array([[1, 2, 5],
       [5, 6, 5]])

In [55]:
d= np.array(((1, 2, 5), (5, 6, 5)))
d

array([[1, 2, 5],
       [5, 6, 5]])

In [56]:
e= np.array([(1, 2, 5),(5,6,7), (5, 6, 5)])
e

array([[1, 2, 5],
       [5, 6, 7],
       [5, 6, 5]])

### Параметр dtype

In [57]:
v= np.array(((1, 2, 5),(5,6,7)), dtype=float)
v

array([[1., 2., 5.],
       [5., 6., 7.]])

### Функции генерации массива

In [58]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [61]:
np.arange(0, 12, 4)

array([0, 4, 8])

In [62]:
np.arange(0, 12, 0.6)

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4,  6. ,
        6.6,  7.2,  7.8,  8.4,  9. ,  9.6, 10.2, 10.8, 11.4])

In [63]:
np.arange(0, 12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [65]:
np.random.random(4)

array([0.15815622, 0.58862823, 0.20828425, 0.69096726])

In [66]:
np.random.random((4,4))

array([[0.78249979, 0.32977106, 0.9298474 , 0.96276089],
       [0.26492047, 0.70379772, 0.22430994, 0.74740191],
       [0.75020512, 0.78058975, 0.39257463, 0.52561706],
       [0.70081845, 0.16690492, 0.48562304, 0.08293594]])

### Индексы и срезы

In [67]:
n=np.array(((1,2,3), (4,5,6), (7,8,9)), dtype=float)
n

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [68]:
n[::-1] #перестановка строк

array([[7., 8., 9.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [69]:
n[:,2]

array([3., 6., 9.])

In [70]:
n[1,2]=10
n

array([[ 1.,  2.,  3.],
       [ 4.,  5., 10.],
       [ 7.,  8.,  9.]])

In [71]:
for i in n:
    print(i**0.5)

[1.         1.41421356 1.73205081]
[2.         2.23606798 3.16227766]
[2.64575131 2.82842712 3.        ]


## NumPy

In [72]:
import numpy as np

In [73]:
# создание массива
list_1 =[0,1,2,3,4]
arr_1d=np.array(list_1)
print(arr_1d)
print(arr_1d.dtype)
type(arr_1d)

[0 1 2 3 4]
int64


numpy.ndarray

In [74]:
h=np.array([[0,2,3,4],[5,6,7,8]])
h.shape

(2, 4)

In [75]:
# Прибавление и вычитание числа
for i in range(len(list_1)):
    list_1[i]+=1
arr_1d +=1
print(list_1)
print(arr_1d)

for i in range(len(list_1)):
    list_1[i]-=1
arr_1d-=1
print(list_1)
print(arr_1d)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [76]:
zeros = np.zeros(10)
ones = np.ones(10)
arange_1=np.arange(10)
linspace_1=np.linspace(0,2,5)

print('zeros', zeros)
print('ones', ones)
print('arange_1', arange_1)
print('linspace_1', linspace_1)

zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
arange_1 [0 1 2 3 4 5 6 7 8 9]
linspace_1 [0.  0.5 1.  1.5 2. ]


In [77]:
print(ones+arange_1)
print(ones*arange_1)
print(ones/arange_1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_4348\604282676.py:3: RuntimeWarning: divide by zero encountered in divide
  print(ones/arange_1)


In [78]:
print(np.arange(10)[5:9])
arange = np.arange(10).reshape(2,5)
print('arrange1=', arange)
print('arrange2=', arange[:,3:])
print('arrange3=', arange[arange%2==1])

[5 6 7 8]
arrange1= [[0 1 2 3 4]
 [5 6 7 8 9]]
arrange2= [[3 4]
 [8 9]]
arrange3= [1 3 5 7 9]


In [79]:
a= np.arange(6)
print(a.shape)
a2=a[np.newaxis, :]
a2.shape

(6,)


(1, 6)

# Pandas

In [80]:
import pandas as pd
df = pd.DataFrame({'int_col':[1,2,6,8,-1], 'float_col':[0.1,0.2,10.1,0.32, None], 'str_col': ['a','b', None, 'c', 'a']})
df

int_col  float_col str_col
0        1       0.10       a
1        2       0.20       b
2        6      10.10    None
3        8       0.32       c
4       -1        NaN       a

In [81]:
cities={"name": ["London", "Berlin", "Madrid", "Rome", "Paris", "Vienna", "Bucharest"],
       "population":[123456,798785,45648645,456456,545644,4545456,6456445],
       "area":[1572,4567,1234,4562,4562,7895,4561]}
city_frame=pd.DataFrame(cities, columns=["population", "area"],
                       index=cities["name"])
print(city_frame)

           population  area
London         123456  1572
Berlin         798785  4567
Madrid       45648645  1234
Rome           456456  4562
Paris          545644  4562
Vienna        4545456  7895
Bucharest     6456445  4561


In [82]:
df.loc[:,['float_col','int_col']]

float_col  int_col
0       0.10        1
1       0.20        2
2      10.10        6
3       0.32        8
4        NaN       -1

# 1.	Использование команд библиотеки NumPy

### 1.1.	Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [83]:
import numpy as np

my_array = np.arange(5, 101, 5)
print("Массив чисел, кратных 5:", my_array)

Массив чисел, кратных 5: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


### 2.1.	Из полученного массива получить массив с кратными 10 числами

In [84]:
my_array_10 = my_array[my_array % 10 == 0]
print("Массив чисел, кратных 10:", my_array_10)

Массив чисел, кратных 10: [ 10  20  30  40  50  60  70  80  90 100]


### 3.1.	Получить двумерный массив с двумя столбцами

In [85]:
two_column = my_array_10.reshape(-1, 2)

print(two_column)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


### 4.1.	Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [86]:
two_column_array_second = two_column - 5

print(two_column_array_second)

[[ 5 15]
 [25 35]
 [45 55]
 [65 75]
 [85 95]]


### 5.1.	Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.

In [87]:
join_array = np.hstack((two_column, two_column_array_second))

print(join_array)

[[ 10  20   5  15]
 [ 30  40  25  35]
 [ 50  60  45  55]
 [ 70  80  65  75]
 [ 90 100  85  95]]


### 6.1.	Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [88]:
division_2nd = join_array[1] / join_array[3]
division_3rd = join_array[2] / join_array[3]

new_join_array = join_array.copy().astype(float)
new_join_array[1] = division_2nd
new_join_array[2] = division_3rd
print(new_join_array)

[[ 10.          20.           5.          15.        ]
 [  0.42857143   0.5          0.38461538   0.46666667]
 [  0.71428571   0.75         0.69230769   0.73333333]
 [ 70.          80.          65.          75.        ]
 [ 90.         100.          85.          95.        ]]


### 7.1.	Оставить только те значения, которые не изменились после деления

In [89]:
equal = np.all(join_array == new_join_array, axis=1)
news = new_join_array[equal]
print(news)

[[ 10.  20.   5.  15.]
 [ 70.  80.  65.  75.]
 [ 90. 100.  85.  95.]]


### 8.1.	Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [90]:
news[[0, 2]] = news[[2, 0]]
print(news)

[[ 90. 100.  85.  95.]
 [ 70.  80.  65.  75.]
 [ 10.  20.   5.  15.]]


### 9.1.	Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().

In [91]:
mean_value = np.mean(news, axis=1)
median_value = np.median(news, axis=1)
std_value = np.std(news, axis=1)

print("Mean:", mean_value)
print("Median:", median_value)
print("STD:", std_value)

Mean: [92.5 72.5 12.5]
Median: [92.5 72.5 12.5]
STD: [5.59016994 5.59016994 5.59016994]


### 10.1.	Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.

In [92]:
max_value = np.max(news, axis=1, keepdims=True)
result = news / max_value
print(result)

[[0.9    1.     0.85   0.95  ]
 [0.875  1.     0.8125 0.9375]
 [0.5    1.     0.25   0.75  ]]


# 2.	Использование команд библиотеки pandas

### 2.1.	Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.

### 2.2.	 Считайте несколько первых записей таблицы (head())
### 2.3.	 Определите размерность данного фрейма (shape())
### 2.4.	 Выведите название заголовков столбцов фрейма (columns)
### 2.5.	Получите описание всех переменных (полей) (info())


In [93]:
import pandas as pd

df = pd.read_csv('Global Population Trends(2016-2022).csv')
print(df.head())
print(df.shape)
print(df.columns)
print(df.info())

       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           - 

### 2.6.	 Удалите строки, не содержащие значения в столбце «Total Population» - “-” 

In [94]:
df1=df[df['Total Population']!='-']
print (df1)

          Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate

### 2.7.	Получите описательную статистику по переменным (например, max(), min(), describe())

In [95]:
print(df1.max())
print(df1.min())
print(df1.describe())
print(df1['Rural Population'].describe())
print(df1['Rural Population'].max())
print(df1['Rural Population'].min())

Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                85.0
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                     5.0
dtype: object
Country                  Afghanistan
Year                            2018
Total Population           1,057,198
Urban Population                   -
Rural Population                   -
Population Density                 -
Life Expectancy                    -
Birth Rate                       0.0
Death Rate                       0.0
Fertility Rate                     -
Infant Mortality Rate              -
Growth Rate                     -1.0
dtype: object
              Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   201

### 2.8.	Выполните сортировку данных по нескольким критериям

In [96]:
df_sort = df1.sort_values(by=['Rural Population','Year','Country'])
print(df_sort.head())

            Country  Year Total Population Urban Population Rural Population  \
104         Bermuda  2018           63,918           63,918                -   
178  Cayman Islands  2018           64,884           64,884                -   
362       Gibraltar  2018           32,648           32,648                -   
417       Hong Kong  2018        7,452,600        7,452,600                -   
502          Kosovo  2018        1,797,085                -                -   

    Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
104              1,184            81.0       8.300       8.300            1.3   
178                270               -       9.900       3.300              -   
362              3,265            82.0      11.242       8.191          1.879   
417              7,098            85.0       7.200       6.400           1.08   
502                  -            79.0      12.094       5.505          1.605   

    Infant Mortality Rate Growth

In [97]:
# Фильтруем данные, убирая строки с нечисловыми значениями в 'Total Population'
df1 = df[df['Total Population'] != '-'].copy()  # Создаем явную копию
df1.loc[:, 'Total Population'] = df1['Total Population'].astype(str).str.replace(',', '').astype(float)
print(df1['Total Population'])

1       36686784.0
2       37769499.0
3       38972230.0
4       40099462.0
6        2866376.0
           ...    
1067    19473125.0
1069    15052184.0
1070    15354608.0
1071    15669666.0
1072    15993524.0
Name: Total Population, Length: 864, dtype: object


### 2.9.	 Выведите название страны, которая имеет максимальную численность населения

In [98]:
country_max_population = df1.loc[df1['Total Population'].idxmax(), 'Country']
print(f"Страна с максимальной численностью населения: {country_max_population}")

Страна с максимальной численностью населения: China


### 2.10.	Выведите название страны, которая имеет минимальную численность населения

In [99]:
country_min_population = df1.loc[df1['Total Population'].idxmin(), 'Country']
print(f"Страна с минимальной численностью населения: {country_min_population}")

Страна с минимальной численностью населения: Tuvalu


### 2.11.	Экспорт фрейма в MS Excel

In [100]:
import pandas as pd
df1.to_excel('Global_Population_Trends.xlsx', index=False)